apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-app-data
  labels:
    app: recommendation-app-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-app-data
  template:
    metadata:
      labels:
        app: recommendation-app-data
    spec:
      containers:
        - name: data-generator
          image: data-generator:latest
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-cluster-kafka-bootstrap.flink.svc:9092"
            - name: DATA
              value: "clickStream,sales"
#            - name: USE_APICURIO_REGISTRY
#              value: "true"
#            - name: REGISTRY_URL
#              value: "http://apicurio-registry-api.flink.svc:8080/apis/registry/v2"